-- 코드를 입력하세요
WITH AVAIABLE_CARS AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 AS RENTAL_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV') 
    AND C.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.START_DATE <= '2022-11-30'
        AND H.END_DATE >= '2022-11-01'
    )
),
DISCOUNTED_FEE AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.RENTAL_FEE - D.DISCOUNT_RATE / 100 * A.RENTAL_FEE AS REAL_FEE
    FROM AVAIABLE_CARS A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
    ON A.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
)
# SELECT CAR_ID 
# FROM AVAIABLE_CARS;

SELECT CAR_ID, CAR_TYPE, CAST(REAL_FEE AS UNSIGNED) AS FEE
FROM DISCOUNTED_FEE D
WHERE REAL_FEE >= 500000 AND REAL_FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC