-- 코드를 작성해주세요
WITH RECURSIVE GENATION AS (
    SELECT ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT E.ID, DEPTH + 1 AS DEPTH
    FROM GENATION G JOIN ECOLI_DATA E
    ON G.ID = E.PARENT_ID
)

# WITH CHILD AS(
#     SELECT E1.ID, COUNT(E2.ID) AS CHILD
#     FROM ECOLI_DATA E1 
#     LEFT JOIN ECOLI_DATA E2
#     ON E1.ID = E2.PARENT_ID
#     GROUP BY E1.ID
# )

SELECT COUNT(ID) AS COUNT, DEPTH AS GENERATION
FROM GENATION 
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY DEPTH
ORDER BY DEPTH
# SELECT COUNT(ID) AS COUNT, DEPTH AS GENERATION
# FROM GENATION JOIN CHILD
# ON CHILD.ID = GENATION.ID
# WHERE CHILD.CHILD = 0
# GROUP BY DEPTH
# ORDER BY DEPTH