-- 코드를 입력하세요
SELECT F.PRODUCT_ID,	PRODUCT_NAME,	TOTAL_AMOUNT * PRICE AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
    GROUP BY PRODUCT_ID) O JOIN FOOD_PRODUCT F
    ON O.PRODUCT_ID = F.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID 
    

