-- 코드를 입력하세요
WITH ORDER_AMOUNT AS (
SELECT FH.FLAVOR, SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS AMOUNT 
FROM FIRST_HALF FH JOIN JULY J
    ON FH.FLAVOR = J.FLAVOR
    GROUP BY FH.FLAVOR
)
SELECT FLAVOR 
FROM ORDER_AMOUNT 
ORDER BY AMOUNT DESC
LIMIT 3;